name: Commits metrics
on:
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: Lsdy one day commit metrics
    runs-on: ubuntu-latest

    steps:
        - name: Check for new commits today
          id: check-new-commits
          uses: adriangl/check-new-commits-action@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            seconds: 86400 # One day in seconds
            branch: 'master'
            
        - name: Print something if new commits are found
          if: ${{ steps.check-new-commits.outputs.has-new-commits == 'true' }}
          run: echo "You have ${{ steps.check-new-commits.outputs.new-commits-number }} new commit(s) ✅!"
        
        - name: Print another thing if new commits couldn't be found
          if: ${{ steps.check-new-commits.outputs.has-new-commits != 'true' }}
          run: echo "You don't have new commits 🛑!"